#!/usr/bin/env node
/**
 * Bumps the patch version in package.json and writes the result (plus a build
 * timestamp) into src/app/core/app-version.ts, so the running app can display
 * exactly which build is live — the whole point being a quick, visible way to
 * confirm a `npm run deploy` actually shipped.
 */
const fs = require('fs');
const path = require('path');

const pkgPath = path.join(__dirname, '..', 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

const [major, minor, patch] = pkg.version.split('.').map((n) => parseInt(n, 10) || 0);
pkg.version = `${major}.${minor}.${patch + 1}`;

fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

const outPath = path.join(__dirname, '..', 'src', 'app', 'core', 'app-version.ts');
const builtAt = new Date().toISOString();
fs.writeFileSync(
  outPath,
  `// Auto-generated by scripts/bump-version.js on every \`npm run deploy\`. Do not edit by hand.\n` +
    `export const APP_VERSION = '${pkg.version}';\n` +
    `export const BUILT_AT = '${builtAt}';\n`
);

console.log(`Bumped version to ${pkg.version} (built ${builtAt})`);
